### ISSUE TITLE
User's selection of the non-method A OA agreement is not persisted between pages.

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#184]
moving away from the page and coming back revert the radio button value to its original value. 

<img width="307" alt="screen shot 2018-04-26 at 9 00 48 pm" src="https://user-images.githubusercontent.com/11050142/39339114-f6eece7e-4994-11e8-8fe4-e289cb941cf6.png">

**Comment by jabrah** [comment]
So the issue was uncovered where a user would make a selection to the radio inputs in the NIH policy card, then proceed as normal. The user then went back to the policy step. At this point, the application would display the policy card with the bottom option selected always, no matter what the previous selection was.

By passing in the `workflow-wrapper.includeNIHDeposit` property to the `workflow-policy` component, we could initialize the state of the radio buttons based on the overall workflow context.

A second issue was uncovered while troubleshooting the first bug. While going through the back-and-forth to determine that the state of the radio buttons was indeed maintained, it was found that the metadata step would hold onto the NIH metadata when it was supposed to be removed:

1. User selects bottom option, which will show PMC in the repositories step.
1. Onto metadata step, as expected, the NIH metadata screen appears.
1. User goes back to policy step to select the top option, removing PMC from the repositories, as expected.
1. Onto the metadata step, the NIH metadata page is shown, when it should not be there.

In the repositories step controller, there is an `addedRepositories` property where new repositories are collected. These are then deposited into the new submission when the user clicks the Next button. When going back and forth in the workflow, this property is never emptied, so when PMC is added in (1) above, it remains in (3) above, thus the NIH metadata page appears in (4)

See my [`fix/nih-radio-input-state`](https://github.com/jabrah/pass-ember/tree/fix/nih-radio-input-state) branch for a possible jumpstart on the issue.

I have poked around in the `workflow-repositories` component, it looks like the component property `addedRepositories` is holding onto its data between steps.
