### ISSUE TITLE
Grant cannot be removed from grant list

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#230]
<img width="1124" alt="screen shot 2018-05-03 at 3 42 30 pm" src="https://user-images.githubusercontent.com/11050142/39599098-afb23ee8-4ee8-11e8-897a-8a7b997fea0d.png">

**Comment by jabrah** [comment]
This seems to be directly related to #238 and has to do with behavior when creating a new submission from the Grant Details page. In this scenario, whether the behavior is intended or not, seeding a new submission with a grant makes it so that specific grant cannot be removed from the submission. 

Do we want this behavior? Or do we want to be able to remove a Grant despite starting the submission from that grant?

**Comment by htpvu** [comment]
I think it can go either way. i can make a case, as long as the behavior after a grant is removed is correct, that is if that grant is removed by the user once inside the workflow, that needs to be reflected in policies displayed, repositories, the submission objects created.

**Comment by htpvu** [comment]
It seems that you guys decided that grant (from which the submission was started) Could not be removed. Then We need to remove the "remove" button. or it'd be really confusing as to why that button is unresponsive.

**Comment by htpvu** [comment]
well i can't verify this now, because i can't seem to preseed the submission with a grant - see ticket https://github.com/OA-PASS/pass-ember/issues/287

**Comment by htpvu** [comment]
Please see my comment  regarding removal of "remove" button above.

**Comment by htpvu** [comment]
verified on rev. caa9e3c7
