### ISSUE TITLE
Add useful tooltip (WIP)

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#319]
on each page, go through and add tooltips where needed

**Comment by htpvu** [comment]
![doi tooltip](https://user-images.githubusercontent.com/11050142/41055886-6eb8a572-6990-11e8-801c-1d017c394157.png)
![screen shot 2018-06-06 at 1 45 11 pm](https://user-images.githubusercontent.com/11050142/41055901-7c6c32e2-6990-11e8-8fce-79065a6f8a89.png)

**Comment by Rytiggy** [comment]
@htpvu 
To make the tooltip fit on the page I had to shorten the text that was provided.
![screen shot 2018-06-07 at 8 06 21 pm](https://user-images.githubusercontent.com/17414914/41133161-42e5a0ea-6a93-11e8-8381-6754575867c3.png)

It is hard to make a tooltip like the above image because this  is rendered through alpacha forms. Thus tooltips in the metadata section are displayed like this. 
![screen shot 2018-06-07 at 8 31 06 pm](https://user-images.githubusercontent.com/17414914/41133153-3b60898e-6a93-11e8-97d9-084562a4c32c.png)

**Comment by Rytiggy** [comment]
As a note for whoever picks this ticket up when adding more tooltips, the syntax looks like this.
```html
  <button tooltip-position="right" tooltip="A digital object identifier (DOI) is a unique alphanumeric string assigned to identify content and provide a persistent link to its location on the Internet.">
    <i class="fas fa-info-circle"></i>
  </button>
```

**Comment by htpvu** [comment]
@Rytiggy I'd rather the DOI tooltip be displayed in the same way the embargo data tooltip is and have all of the information than truncating the message. Can it be made that way?

**Comment by Rytiggy** [comment]
@htpvu  is this what you were thinking? ![screen shot 2018-06-08 at 9 33 36 am](https://user-images.githubusercontent.com/17414914/41160917-14d9b6a2-6aff-11e8-8c5f-e025159b2043.png)
