### ISSUE TITLE
We need a file upload service so we can save submission file binary data

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#346]
Need confirmation where we should save the binary data. Currently sounds like the assumption is that the data will go into Fedora.

**Comment by birkland** [comment]
Yes, binary data should be in Fedora.

In general, binary content is created by `POST`ing it to a resource.  Since binary files are truly scoped to a single submission, it might make sense to `POST` the binary to the `Submission` resource.  So the workflow would be:

1. Create a submission, say it ends up as `http://example.org/pass/submissions/foo`
2. POST the binary contents the submission to the submission at its URI: `http://example.org/pass/submissions/foo`
   * This will create a binary resource at `http://example.org/pass/submissions/foo/bar`
   * Make sure to set the `Content-Type` header to the proper media type, or `application/octet-stream` if not known.
   * If you want to, you can specify the file name (i.e. if someone subsequently downloads the file) via the header `Content-Disposition: attachment; filename="foo.jpg"`
3. Have Ember create a `File` entity as it usually does, but make sure to link to the binary resource
   * In the `File` entity, make sure `"uri" : "http://example.org/pass/submissions/foo/bar"`
   * I think Ember rigidly expects `File` entities to be under `files`, which is fine.  The native LDP way to do it would be to put the `File` entity at the URI pointed to by the `describedBy` link header of the binary, but I don't think the Ember adapter would be able to do that without some work; so we can ignore that alternative

**Comment by htpvu** [comment]
verified on rev. b0b535cb
