### ISSUE TITLE
Finalize the static landing pages for PASS

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#570]
with the code for static pages in the pass-ember repo

**Comment by JeffSpies** [comment]
Summary: don't create a second repo for programmatically built files. Instead, point one VirtualHost to the dist/ folder (or whatever folder you config to the be the dist location of the build process) where those files get built from the repo that builds them.

More:

The static files that are copied to OA-PASS/pass-ui-static are built in this repo. Rather than duplicating the files (and then versioning duplicates and having to manage synchronization), the standard way to handle this would be to point the VirtualHost at the relevant folder in OA-PASS/pass-ember/dist/ after running "ember build" rather than a separate repo. If the Apache server points two VirtualHosts at the same filesystem, then these files will likely exist in OA-PASS/pass-ember/dist/ because the second VirtualHost (the protected Ember app, as I understand it) will have run that as part of being started. (Aside: you can change the build function to put files in any folder; so a production config may have its "dist" folder in /web/frontend/static/).

CC @htpvu . Happy to say more if it helps you avoid today's conversation; this is pretty standard, and I can work with someone else directly if that'd be helpful.

**Comment by htpvu** [comment]
Thanks @JeffSpies I'll ask someone to read and see how to move forward. We'll ping you with questions.

**Comment by birkland** [comment]
@htpvu Right now, this task is not defined enough for it to be actionable.   I'm really not sure what the end goal is, and how the pass-ui-static repository is related to anything.  So how about I explain where we are right now, then we can flesh out what we need to do.

As @JeffSpies mentioned, the way we deploy the ember app now is to run `ember build --environment=production`.  This creates a directory of static files (an `index.html`, and various fonts, js files, etc) that is being served up, which is then accessible on the web under `/app/`

So in `pass-docker`, we have:
* `/index.html`  - a bare bones "public landing page" that links to the UI in `/app`.  It is publicly accessible, _not_ protected by shibboleth.  Right now, it is just hand-written un-styled HTML
* `/app/index.html` - The ember UI.  This is the page you see when you first look at when you see the ember app.  It is generated with `ember build`, as is everything else in the `/app` directory.  `/app` is shibboleth protected; you need to be logged in to see the ember app in the first place.

The origin and intent of `pass-ui-static` are unclear to me, but it _looks_ like it is a dump from some past version of the ember app, with some additional (manual?) tweaks.  At this point, I don't know the ember app well enough to distinguish the enhancements from auto-generated Ember parts.

So I guess my first question is "are the contents of `pass-ui-static` intended to be the public landing page, accessible at `/index.html` _linking_ to the ember app at `/app/index.html`"?  The answer to that question will help me frame and parse the various issues.

**Comment by birkland** [comment]
Discussion with @htpvu clarified a few things:

The `pass-ui-static` repo is intended to be PASS public landing page (i.e. `/index.html` and friends).  So it should:
* Be welcoming, and informative, with helpful information such as a FAQ, contact, and about pages
* Prominently link to the Ember UI, so that people can click on it to use PASS (If they're not already logged in, shibboleth will intercept the request and take them on a detour through their institutional login when they click on the link to `/app`).
* Contain a few "nice" error pages for the ember app to redirect to if something goes wrong (e.g. a user does something unauthorized and the repo returns a 401)

While the contents of `pass-ui-static` look like a dump and tweak of an ember app, there doesn't seem to be any specific reason that the static pages need to be that way.  A few html pages is all that is needed in this repo, but it's up to the judgement of the UI folks.  To the systems folks, this repo will be a black box that is pretty much deployed verbatim.

**Comment by JeffSpies** [comment]
Is this now about deploying or creating/editing (i.e., finalizing) the landing page and all of the associated pages/behavior?

If deploying:

The repository gh:pass-ui-static, at this point, is just a vehicle to get files to the server (i.e., git clone gh:pass-ui-static). But those static files will already be on the server or can be better connected (i.e., not sync'd) to their origin if we do as you, @birkland, mentioned [above](https://github.com/OA-PASS/pass-ember/issues/570#issuecomment-398391997). I'd suggest doing that.

If not, this (as a deploy ticket) could just specify for whomever is deploying the code that every time the repo (or just the static content) is updated, run ember build somewhere, copy the static files to another folder, git commit them to gh:pass-ui-static, git push them, and then git pull them from the server. @htpvu, as a deploy ticket, this is better left for a systems person to decide and take on; as specified, Ryan can certainly copy files to that repo on Friday, but I'd worry that any urgent changes in the future would include him as a dependency.

**Comment by htpvu** [comment]
@JeffSpies @birkland This is about creating and editing the public pages. 

The goal is to have public pages available outside of the ember app, in front of shib. Since the to-be-made-public pages (landing, about, etc) are currently part of the ember app, ember does not generate static html pages for them. Since they are not generated, we have nothing to deploy. However this happens, we need these static pages to be available so that we can deploy them. For the purpose of getting the html files from developers to sys admin, it could be in the `pass-ui-static` repo, it could be in a folder in the `pass-ember` repo. 

HTML pages currently in `pass-ui-static` repo are out of date, we can't deploy these either.

If this doesn't clear up what needs to be done, let's have a phone call. Please send me your availability.

**Comment by birkland** [comment]
So we already have a process for managing the ember app at `/app`, independent of whatever is happening here.  

If the end result is that the contents of the `pass-ui-repo` can be blindly copied into `/` (independently of whatever is going in in the ember app), then I think we're good.  If the end result requires a different process, then do loop me and Derek in on it.

**Comment by JeffSpies** [comment]
Alright, according to @Rytiggy, the landing page and error pages are done. We'll make those displayable in a bit. Then, upon seeing them, if there are changes required, new tickets can be created.

**Comment by htpvu** [comment]
@JeffSpies @Rytiggy actually the landing page as it is in the this repo https://github.com/OA-PASS/pass-ui-static is not done. 
Amongst other updated that had been made in the pass-ember codebase to have the landing page rendered differently, there is a ticket for making the header of the page rotate around some images (https://github.com/OA-PASS/pass-ember/issues/402)

Additionally, will you guys make the other public pages displayable as well? About, Contact, and FAQ.
Thanks.

**Comment by JeffSpies** [comment]
Right, you can't see them yet. That's what we're working on. And the rotate
image ticket (#402) is currently assigned to Cam, so we're on it.

**Comment by htpvu** [comment]
Cool. thanks very much!

**Comment by JeffSpies** [comment]
@htpvu here is the current static site sans text changes that I think you're working on.

http://pass-static.surge.sh/

cc @Rytiggy

**Comment by htpvu** [comment]
@JeffSpies the fonts used are not ones we are supposed to use. I'm not sure what is needed for the right fonts to display. if it's something we need to provide, please let meknow. @Rytiggy was the one who brought the site into compliance with JHU styleguide, perhaps he could do that gain?

**Comment by JeffSpies** [comment]
That may be an asset not getting copied over. @rytiggy, can you update it?

**Comment by htpvu** [comment]
@Rytiggy could you please point me to where the static files are? or how we can get them?
