### ISSUE TITLE
When loading grant table for faculty1 user, UI is asking to see grants it doesn't have access to

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#684]
UI should only be asking for grants that the current user is a PI or Co-PI of.

**Comment by karenhanson** [comment]
So, the code that seems to be causing the problem is this:

https://github.com/OA-PASS/pass-ember/blob/def62bf28ddcb36887982e17663036d5b2364ac2/app/routes/grants/index.js#L64-L73

If my understanding is correct, that block of code retrieves all submissions for a grant, and then all grants for each submission. When it retrieves the grants for that submission, it has a chance of running into a grant that is not the logged in users'. That is the when you get a 403. In the specific instance we are seeing:

`faculty1` is co-pi on this grant: 
http://fcrepo:8080/fcrepo/rest/grants/59/b8/5f/d0/59b85fd0-ba81-47e1-bc33-475a877fb0cf
This grant is part of a submission by the grant's PI: 
http://fcrepo:8080/fcrepo/rest/submissions/af/93/ff/e8/af93ffe8-d386-47e6-a5e1-4c04d88943d7
The same submission cites a second grant that `faculty1` is not a part of:
http://fcrepo:8080/fcrepo/rest/grants/25/e0/a3/70/25e0a370-679d-45de-98d1-fd8f9a3e4dd0
When it tries to retrieve this, you get the 403.

**Comment by karenhanson** [comment]
I think there is an argument to be made that no ember change is needed here. If we change the ACLs per the policy doc so everyone can read every grant in Fedora. Problem solved.

The alternative is to filter the grants shown against a submission according to whether the user is a PI/Co-PI.

**Comment by htpvu** [comment]
yes I agree, let's pursue the route that lets every logged in users see all grants.
