### ISSUE TITLE
Status sort on Submission table does not sort as expected

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#685]
Log in as `nih-user`, go to Submissions page, click the Status header, the column does not sort as expected.

**Comment by cameronblandford** [comment]
This could be anywhere from 5 minutes to 6 hours, depending on the issue. Will provide a better estimate after some investigation.

**Comment by cameronblandford** [comment]
This isn't so much a bug as it is an improper implementation - ember-model-tables handles sorting by alphabetically sorting the `propertyName` value of each column, in this case `aggregatedDepositStatus`. In order to get the sorting to work properly, all of the status computation would have to take place not in the cell but in a computed value on the model, so it would be accessible as the column/cell's `propertyName`.

**Comment by karenhanson** [comment]
This was fixed when status display was updated
