### ISSUE TITLE
Review and recommend next steps with regarding to testing n pass-ember code base

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#753]
Review the outcome of this ticket https://github.com/OA-PASS/pass-ember/issues/752 - recommend next course of action.

**Comment by markpatton** [comment]
Whenever an ember object (route, component, controller, template, service, etc.) is generated, a corresponding test is generated. These smoke tests are very useful for making sure that the componenet can at least be instantiated. The large majority of all the tests are smoke tests.

There are three types of tests: unit, integration, and acceptance. Unit tests check the behavior of an ember object in isolation. Adapters, Controllers, Models, Routes, Serializers, and Services have unit tests. With the exception of a couple services, all of the unit tests are smoke tests. Integration tests check the behavior of Ember objects that render the UI such as Components and Helpers. (Why they are called integration tests instead of unit tests is not enirely clear.) Most of the integration tests are smoke tests. Acceptance tests are different from the other two. Acceptance tests actually start the application and simulates user actions in order to test the application behavior. Generally each route in the application should have an acceptance test. There are acceptance tests for the grant table and detail views, logging in, the submission table and creating a new submission. Most of these tests are actually testing behavior, although the new submission test is mostly commented out.

Acceptance tests start the whole application which means external dependencies like Fedora and Elasticsearch must either be available or mocked.
There is a docker-compose.yml at the root of pass-ember which was originally intended to be used for testing. It includes Fedora, Elasticsearch, and PASS Indexer. The user service appears to be mocked. Travis is setup to start these containers and run the ember tests. The last work on the acceptance tests was by John in June 2018.

But the tests don't work. Of the 307 tests, 47 fail. In particular all the acceptance tests fail. This indicates that the framework for running the acceptance tests is wrong or out of date. The unit test errors can probably be figured out without much trouble.

This is based off of looking at the feature/proxy-submitter branch. I also looked at the Add Proxy Feature PR, but the test code appears to be the same.

After reading the testing report, I agree that the most important step is to have real unit and integration tests. Smoke tests are necessary, but they are not sufficient. Ideally these are tests that could be run without the support of external dependencies like Fedora et al. Then we could simply remove the current broken acceptance testing framwork and tests based on docker. In addition, there is code sprinkled throughout the app, that should really be pulled out into separate services which can be better tested. A good example is file upload embedded in app/controllers/submissions/new.js.

At some point it would be useful to be able to write acceptance tests. But this would require a week or so of work to figuring out a reasonable testing framework.
