### ISSUE TITLE
"New Submission" button on grant details looks like it's greyed out

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#76]
![screen shot 2017-12-11 at 10 11 17 am](https://user-images.githubusercontent.com/11050142/33840290-7593c886-de62-11e7-8d11-2534e1563eb7.png)

Could we make it a regular color?

**Comment by htpvu** [comment]
![screen shot 2017-12-11 at 10 57 54 am](https://user-images.githubusercontent.com/11050142/33840360-b37bc018-de62-11e7-89e7-3f8103a2ed65.png)

**Comment by jabrah** [comment]
To me, it looks like this issue comes from Ember.

This button is generated by this bit from `grants/show.hbs` template:
```
{{#link-to 'grants' class="btn btn-primary btn-small"}}Back to grants{{/link-to}}
```

From the Ember docs (https://guides.emberjs.com/v2.5.0/templates/links/):
> When the rendered link matches the current route, and the same object instance is passed into the helper, then the link is given class="active".

So it looks like Ember is adding the 'active' class to this link, which Bootstrap uses to change the color. Not yet sure how to fix this behavior in Ember.

**Comment by Rytiggy** [comment]
This shouldn't be an issue one @cameronblandford  and myself make the PR for our UI changes.
