### ISSUE TITLE
investigate the work involve in rebranding PASS for a different institution

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#877]
The rebranding work should result in the following:
- Institutionally appropriate logos
- Institutionally appropriate header images on the index pay
- Institutionally appropriate colors for headers and buttons
- Institutionally appropriate fonts

The outcome of this ticket should describe the work needed to implement rebranding, including any refactoring work. ***Please also describe the work needed to enable us to maintain multiple brands in parallel.***

**Comment by jabrah** [comment]
### Colors

* Parameterize element colors
  * Extract hard-coded colors from CSS rules to SCSS variables
  * In some cases, create and assign new CSS classes to apply color

What elements need custom colors?

* Navbar (the "header")
* Nav links
* Clickable links
* Buttons
  * Outlined buttons
    - Remove
    - Finish submission
  * Primary buttons
    - Next
    - New Submission
    - View submissions
    - Manage grants' submissions
  * Pagination buttons?
* General text
  * "Subtitle" like text
* Table borders
* Card borders

### Fonts

Fonts are currently defined in `index.html` because we needed to use a parameter that is not accessible from the CSS files. In order to customize fonts
### Images

* Header logo + link will need to be configured somehow, and the widgets will need to be modified to accept configuration
* **Header images on index page - does this refer to the carousel of images on the PASS landing page?** That widget is currently hard coded, so if this needs to be customized, it must either be rewritten to accept lots of configuration, or we would have to drop in a replacement page.

### Other

At the very least, the Contact page needs to be customized for different institutions.

There is also the problem of dealing with the static UI pages. The previous way they were generated was fully manual and not a sustainable process.

**Comment by jabrah** [comment]
### Maintaining multiple brands

I think the simplest thing we can do here is to keep all asset files for all brands together in the master branch in `pass-ember`. We would then have to modify the Ember build process to use different build environments for each brand. This should allow us to swap appropriate assets during the build.

### Maintaining static pages

**Comment by jabrah** [comment]
### Internationalization

This topic was brought up while talking with Mark, but if we're changing the look and text of PASS, we might also want to support different languages. This is beyond the current "branding" scope, however, as this would be a very significant change, requiring the modification of every template and possibly some `app/routes` JS files.

* `ember-i18n` : https://www.npmjs.com/package/ember-i18n
* `ember-intl` : https://github.com/ember-intl/ember-intl

**Comment by htpvu** [comment]
@jabrah supporting different language is not on the horizon for us right now. I wouldn't worry about it?

Given your investigation so far, how many days are required to refactor the styling/branding code so that it can be rready to be rebranded? Once the refactoring happen, how many days would it take to switch PASS from 1 brand to another?

**Comment by jabrah** [comment]
@htpvu I think two weeks should be fine to make changes above. 

Switching between brands, perhaps is not exactly the best phrase. The idea would be to basically be brand agnostic during development, then introduce branding stuff at build time. If we have the right Ember profiles and/or environment variables, building different "brands" would ideally just be a matter of defining the right environment variables.
