### ISSUE TITLE
Include the DOI of the published article in the metadata blob

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/pass-ember#936]
If a user enters a DOI during submission, it ought to be captured in the metadata blob.  Prior to CMF implementation, DOI was captured, and some agents may expect it to be there.  

This is the case with respect to the NIH package provider: it will include the article DOI in package metadata when preparing and depositing a package to NIHMS.  

For reference, the DOI is documented in the [global](https://github.com/OA-PASS/metadata-schemas/blob/master/schemas/jhu/global.json) schema.

If we opt not to capture the DOI, we should discuss the rationale and document it here.

**Comment by jabrah** [comment]
Current UI behavior will trim Crossref data to only those fields that are directly defined by schemas from the schema service. Since not all `global` properties may appear in these schemas, some `global` properties such as DOI are removed from the blob.

As a short-term fix, we can modify the UI behavior to include all `global` properties

**Comment by jabrah** [comment]
Ember impl note:

`services/metadata-schema#getFields` is used to trim Crossref data. There are more fields that appear in the `allOf` validation rule set that come from the global schema.

**Comment by jabrah** [comment]
I currently see two possible workarounds for this:

1) Inspect the schemas we get from the schema service. The schemas include a reference to the global schema as a validation requirement, with the global schema embedded in the schema's `allOf` field. The properties can be used when deciding which Crossref fields to keep. This option will "just work" in other environments/instances, however it is not guaranteed that any set of schema used during a submission will include a "global" schema in their validation rules, as described here
2) Due to a recent change that added `$schema` to the metadata blob, the Ember app is aware of the global schema in it's configuration. We can explicitly load the global schema and use it to determine which Crossref fields to keep. This approach guarantees that all "global" fields are included without relying on the fields to be present in validation rules of other schema, but requires that Ember have knowledge of the instance's "global" schema - for example, a pilot instance would need to know the correct global schema.

**Comment by markpatton** [comment]
We need to define precisely how crossref data should be mapped to the metadata blob and how that is influenced by the schema service.

**Comment by emetsger** [comment]
> but requires that Ember have knowledge of the instance's "global" schema - for example, a pilot instance would need to know the correct global schema

@jabrah can you elaborate on this?  What do you mean by "know the correct global schema" or "knowledge of the instance's 'global' schema"?  Do you mean that the metadata blob must carry `$schema` and its value must be a schema that contains the properties to be included in the blob?
