### ISSUE TITLE
dev instance - deleted drafts don't go away

### ISSUE THREAD

**Issue by jrmartino** [OA-PASS/pass-ember#949]
this happens in dev with issue 17 
steps:
1. try to create submission, see error trying policy service
2. look at submission - see an incomplete submission
3. delete this incomplete submission
4. try another submission, get same policy service error
5. look at submission list, see both incomplete submissions

**Comment by htpvu** [comment]
Additionally, Edit button on the incomplete submission does not work.

**Comment by jabrah** [comment]
Edit button unrelated, but fixed

**Comment by jabrah** [comment]
Instead of issuing DELETE requests when "deleting" draft submissions, we can keep these objects, but change the `submissionStatus` to some other status. `cancelled` may be a good candidate that would not require any changes to the model.

We would have to investigate the submission display logic; whether cancelled submissions are displayed, etc.

Implications of "cancelling" draft submissions are the same as cancelling prepared submissions (as in the proxy submission use case). Any associated Publication object and Files objects would remain in the back end, but the Submission object would not be editable any more.
